/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 31fbe86cc2a8d28bd35b8912c01e9d69)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	ASSETS: Fetcher;
	AUTH_URL: "http://localhost:3000" | "https://ielts-writing-app.tomo9634.workers.dev";
	AUTH_TRUST_HOST: "true";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface StagingEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		AUTH_URL: "http://localhost:3000";
		AUTH_TRUST_HOST: "true";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_URL" | "AUTH_TRUST_HOST">> {}
}
