import type { DailyContent } from './types'

export const PREVIEW_DATE = '2026-07-18'

export function isPreviewMode(): boolean {
  return process.env.AUTH_BYPASS === 'true'
}

export const PREVIEW_DAILY_CONTENT: DailyContent = {
  vocab: [
    {
      order: 1,
      word: 'fluctuate',
      choices: ['to remain unchanged', 'to rise and fall irregularly', 'to remove completely', 'to compare two groups'],
      answerIndex: 1,
      meaning: '上下に変動する。Task 1で数値の動きを説明するときに使う。',
      etymology: 'flu / flow（流れる）に近い音から、数値が一定せず流れるように動くイメージ。',
      synonyms: 'vary / change / fluctuate: fluctuate は上下に揺れる変動、vary は違いがある、change は広く変化を表す。',
      usageTip: 'グラフで数値が上がったり下がったりする時は fluctuate between A and B が使いやすい。',
      mnemonic: 'fluctuate = flowのように数値がふらふら動く。',
      example: 'The figure fluctuated between 40% and 55% throughout the period.',
      exampleJa: 'その数値は期間を通じて40%から55%の間で変動した。',
    },
    {
      order: 2,
      word: 'proportion',
      choices: ['割合', '急落', '平均値', '例外'],
      answerIndex: 0,
      meaning: '全体の中で占める割合。percentage/shareと近い。',
      etymology: 'pro（前へ）+ portion（一部分）で、全体に対する部分。',
      synonyms: 'share / percentage / proportion: proportion は全体に対する部分、percentage は%表示、share は占める分をやや日常的に表す。',
      usageTip: 'Task 1では the proportion of + 複数名詞 + 動詞ing の形で、割合の主語を作りやすい。',
      mnemonic: 'portion（一部）を全体に対して見ると proportion。',
      example: 'A large proportion of students preferred online courses.',
      exampleJa: '学生の大きな割合がオンライン授業を好んだ。',
    },
    {
      order: 3,
      word: 'approximately',
      choices: ['exactly', 'suddenly', 'around', 'separately'],
      answerIndex: 2,
      meaning: 'およそ、約。正確な数字ではなく概数を述べる時に使う。',
      etymology: 'approximate（近づける）から。数字を近似するイメージ。',
      synonyms: 'about / roughly / approximately: approximately は書き言葉寄り、roughly はざっくり感が強く、about は最も一般的。',
      usageTip: 'IELTS Task 1では正確な数値でない時に approximately 70% のように置くと自然。',
      mnemonic: 'approx = だいたい近い。',
      example: 'Approximately 70% of respondents chose public transport.',
      exampleJa: '回答者のおよそ70%が公共交通機関を選んだ。',
    },
    {
      order: 4,
      word: 'whereas',
      choices: ['because', 'while in contrast', 'therefore', 'for example'],
      answerIndex: 1,
      meaning: '一方で。2つの対象を対比するときに便利。',
      etymology: 'where + as から発展し、節同士を対比する接続詞になった。',
      synonyms: 'while / by contrast / whereas: whereas は2つの節をきれいに対比し、by contrast は文頭で対比を強める。',
      usageTip: 'A increased, whereas B declined のように、逆方向の傾向を1文でまとめる時に便利。',
      mnemonic: 'whereas は「Aはこう、 whereas Bはこう」。',
      example: 'Car use increased, whereas bus use declined.',
      exampleJa: '車の利用は増えた一方で、バスの利用は減少した。',
    },
    {
      order: 5,
      word: 'account for',
      choices: ['to explain or make up a share', 'to delete a record', 'to argue against', 'to copy a sentence'],
      answerIndex: 0,
      meaning: '割合を占める、または理由を説明する。Task 1では「占める」が頻出。',
      etymology: 'accountは説明・計算の意味を持つ。数値を説明する句。',
      synonyms: 'make up / represent / account for: account for は割合を占める時に硬めで自然、make up は少し平易。',
      usageTip: '割合を書く時は accounted for + 数値、理由を書く時は account for the change のように使い分ける。',
      mnemonic: '数字のaccountを取る = 何%を占める。',
      example: 'Renewable energy accounted for 30% of total production.',
      exampleJa: '再生可能エネルギーは総生産量の30%を占めた。',
    },
    {
      order: 6,
      word: 'decline',
      choices: ['to increase sharply', 'to decrease', 'to stay flat', 'to recover fully'],
      answerIndex: 1,
      meaning: '減少する。名詞でも「減少」。',
      etymology: 'de-（下へ）+ cline（傾く）で、下向きに傾くイメージ。',
      synonyms: 'decrease / fall / decline: decline は書き言葉で自然、fall はグラフ説明で短く、decrease は中立的。',
      usageTip: '数字がゆるやかに下がる時は declined gradually、急落なら fell sharply の方が合う。',
      mnemonic: 'de = down。decline = downに向かう。',
      example: 'The number of visitors declined after 2018.',
      exampleJa: '訪問者数は2018年以降減少した。',
    },
    {
      order: 7,
      word: 'peak',
      choices: ['lowest point', 'highest point', 'middle value', 'unchanged period'],
      answerIndex: 1,
      meaning: '最高点、ピークに達する。',
      etymology: '山の頂上を表す語から、数値の最高点にも使う。',
      synonyms: 'reach a high / peak / hit the highest point: peak は動詞で短く書け、reach a high は少し説明的。',
      usageTip: '最高値を書く時は peaked at + 数値 + in + 年 の形が一番コンパクト。',
      mnemonic: '山のpeak = グラフの一番高いところ。',
      example: 'Sales peaked at 120 million dollars in 2022.',
      exampleJa: '売上は2022年に1億2000万ドルでピークに達した。',
    },
    {
      order: 8,
      word: 'stable',
      choices: ['changing rapidly', 'not changing much', 'very expensive', 'difficult to measure'],
      answerIndex: 1,
      meaning: '安定した。数値が大きく変わらない状態。',
      etymology: 'sta / stand（立つ）のイメージで、ぐらつかず同じ状態を保つ。',
      synonyms: 'steady / stable / unchanged: stable は安定、steady は安定して続く、unchanged は変化なしを強調。',
      usageTip: '数値がほぼ同じなら remained stable、完全に変化なしなら remained unchanged が合う。',
      mnemonic: 'stable table = ぐらつかない机。数値もぐらつかない。',
      example: 'The unemployment rate remained stable at about 5%.',
      exampleJa: '失業率は約5%で安定していた。',
    },
    {
      order: 9,
      word: 'significant',
      choices: ['minor or unimportant', 'large or important', 'temporary', 'unclear'],
      answerIndex: 1,
      meaning: '著しい、重要な。変化や差が大きい時に使う。',
      etymology: 'signify（意味する）と同根で、意味のある大きさ。',
      synonyms: 'considerable / substantial / significant: significant は重要性や目立つ差、considerable は量の大きさ、substantial は十分な大きさを強調。',
      usageTip: '大きく意味のある変化には significant increase、小さい変化には slight increase を使う。',
      mnemonic: 'significant = サインが出るほど目立つ。',
      example: 'There was a significant increase in spending on education.',
      exampleJa: '教育支出には著しい増加が見られた。',
    },
    {
      order: 10,
      word: 'overall',
      choices: ['in general', 'in one small category only', 'after the chart', 'with no comparison'],
      answerIndex: 0,
      meaning: '全体として。Task 1のoverviewで使いやすい。',
      etymology: 'over + all で、全体を上から見るイメージ。',
      synonyms: 'in general / broadly / overall: overall はoverviewで自然、in general は一般論、broadly は大まかに見る時。',
      usageTip: 'Task 1のoverview冒頭では Overall, + 主な傾向 の形で細かい数字を避ける。',
      mnemonic: 'over all = 全部を見渡して。',
      example: 'Overall, the use of renewable energy increased steadily.',
      exampleJa: '全体として、再生可能エネルギーの利用は着実に増加した。',
    },
  ],
  sentences: [
    {
      order: 1,
      word: 'whereas',
      ja_sentence: '車の利用は増えた一方で、バスの利用は減少した。',
      model_answer: 'Car use increased, whereas bus use declined.',
      tips: 'whereas は2つの対照的な傾向を1文でまとめる時に便利です。',
      explanation: 'Task 1では「A increased, whereas B declined」の形を覚えると、比較を短く自然に書けます。whileも使えますが、whereasの方が少し書き言葉らしい響きです。',
    },
    {
      order: 2,
      word: 'account for',
      ja_sentence: '再生可能エネルギーは総発電量の約30%を占めていた。',
      model_answer: 'Renewable energy accounted for approximately 30% of total electricity production.',
      tips: 'accounted for + 数値 は「占めた」。approximatelyを添えると概数表現になります。',
      explanation: '「占める」は made up でも書けますが、accounted for はIELTS Task 1で非常に使いやすい表現です。total electricity production のように、何の全体かも明確にしましょう。',
    },
    {
      order: 3,
      word: 'peak',
      ja_sentence: '売上は2022年に1億2000万ドルでピークに達した。',
      model_answer: 'Sales peaked at 120 million dollars in 2022.',
      tips: 'peak at + 数値 + in + 年 の形で、最高点を簡潔に表せます。',
      explanation: 'reached a peak of 120 million dollars でもOKです。動詞 peak を使うと短く、グラフ説明らしい文になります。',
    },
    {
      order: 4,
      word: 'overall',
      ja_sentence: '全体として、オンライン学習を選ぶ学生の割合は着実に増加した。',
      model_answer: 'Overall, the proportion of students choosing online learning increased steadily.',
      tips: 'Overall はoverviewの冒頭に置きやすい語です。the proportion of students choosing... で「〜を選ぶ学生の割合」。',
      explanation: 'Task 1のoverviewでは細かい数字を全部書くより、全体傾向を1文で言うことが大切です。increased steadily は「着実に増えた」という自然な表現です。',
    },
  ],
}
