import type { DailyContent } from './types'

export const PREVIEW_DATE = '2026-07-18'

export function isPreviewMode(): boolean {
  return process.env.AUTH_BYPASS === 'true'
}

export const PREVIEW_DAILY_CONTENT: DailyContent = {
  vocab: [
    {
      order: 1,
      word: 'fluctuate',
      choices: ['to remain unchanged', 'to rise and fall irregularly', 'to remove completely', 'to compare two groups'],
      answerIndex: 1,
      meaning: '上下に変動する。Task 1で数値の動きを説明するときに使う。',
      etymology: 'Latinの fluctus（波）に由来し、波のように揺れるイメージ。',
      mnemonic: 'fluctuate = flowのように数値がふらふら動く。',
      example: 'The figure fluctuated between 40% and 55% throughout the period.',
      exampleJa: 'その数値は期間を通じて40%から55%の間で変動した。',
    },
    {
      order: 2,
      word: 'proportion',
      choices: ['割合', '急落', '平均値', '例外'],
      answerIndex: 0,
      meaning: '全体の中で占める割合。percentage/shareと近い。',
      etymology: 'pro（前へ）+ portion（一部分）で、全体に対する部分。',
      mnemonic: 'portion（一部）を全体に対して見ると proportion。',
      example: 'A large proportion of students preferred online courses.',
      exampleJa: '学生の大きな割合がオンライン授業を好んだ。',
    },
    {
      order: 3,
      word: 'approximately',
      choices: ['exactly', 'suddenly', 'around', 'separately'],
      answerIndex: 2,
      meaning: 'およそ、約。正確な数字ではなく概数を述べる時に使う。',
      etymology: 'approximate（近づける）から。数字を近似するイメージ。',
      mnemonic: 'approx = だいたい近い。',
      example: 'Approximately 70% of respondents chose public transport.',
      exampleJa: '回答者のおよそ70%が公共交通機関を選んだ。',
    },
    {
      order: 4,
      word: 'whereas',
      choices: ['because', 'while in contrast', 'therefore', 'for example'],
      answerIndex: 1,
      meaning: '一方で。2つの対象を対比するときに便利。',
      etymology: 'where + as から発展し、節同士を対比する接続詞になった。',
      mnemonic: 'whereas は「Aはこう、 whereas Bはこう」。',
      example: 'Car use increased, whereas bus use declined.',
      exampleJa: '車の利用は増えた一方で、バスの利用は減少した。',
    },
    {
      order: 5,
      word: 'account for',
      choices: ['to explain or make up a share', 'to delete a record', 'to argue against', 'to copy a sentence'],
      answerIndex: 0,
      meaning: '割合を占める、または理由を説明する。Task 1では「占める」が頻出。',
      etymology: 'accountは説明・計算の意味を持つ。数値を説明する句。',
      mnemonic: '数字のaccountを取る = 何%を占める。',
      example: 'Renewable energy accounted for 30% of total production.',
      exampleJa: '再生可能エネルギーは総生産量の30%を占めた。',
    },
    {
      order: 6,
      word: 'decline',
      choices: ['to increase sharply', 'to decrease', 'to stay flat', 'to recover fully'],
      answerIndex: 1,
      meaning: '減少する。名詞でも「減少」。',
      etymology: 'de（下へ）+ clinare（傾く）で、下向きに傾くイメージ。',
      mnemonic: 'de = down。decline = downに向かう。',
      example: 'The number of visitors declined after 2018.',
      exampleJa: '訪問者数は2018年以降減少した。',
    },
    {
      order: 7,
      word: 'peak',
      choices: ['lowest point', 'highest point', 'middle value', 'unchanged period'],
      answerIndex: 1,
      meaning: '最高点、ピークに達する。',
      etymology: '山の頂上を表す語から、数値の最高点にも使う。',
      mnemonic: '山のpeak = グラフの一番高いところ。',
      example: 'Sales peaked at 120 million dollars in 2022.',
      exampleJa: '売上は2022年に1億2000万ドルでピークに達した。',
    },
    {
      order: 8,
      word: 'stable',
      choices: ['changing rapidly', 'not changing much', 'very expensive', 'difficult to measure'],
      answerIndex: 1,
      meaning: '安定した。数値が大きく変わらない状態。',
      etymology: 'standに近い語源で、しっかり立っているイメージ。',
      mnemonic: 'stable table = ぐらつかない机。数値もぐらつかない。',
      example: 'The unemployment rate remained stable at about 5%.',
      exampleJa: '失業率は約5%で安定していた。',
    },
    {
      order: 9,
      word: 'significant',
      choices: ['minor or unimportant', 'large or important', 'temporary', 'unclear'],
      answerIndex: 1,
      meaning: '著しい、重要な。変化や差が大きい時に使う。',
      etymology: 'signify（意味する）と同根で、意味のある大きさ。',
      mnemonic: 'significant = サインが出るほど目立つ。',
      example: 'There was a significant increase in spending on education.',
      exampleJa: '教育支出には著しい増加が見られた。',
    },
    {
      order: 10,
      word: 'overall',
      choices: ['in general', 'in one small category only', 'after the chart', 'with no comparison'],
      answerIndex: 0,
      meaning: '全体として。Task 1のoverviewで使いやすい。',
      etymology: 'over + all で、全体を上から見るイメージ。',
      mnemonic: 'over all = 全部を見渡して。',
      example: 'Overall, the use of renewable energy increased steadily.',
      exampleJa: '全体として、再生可能エネルギーの利用は着実に増加した。',
    },
  ],
  sentences: [
    {
      order: 1,
      word: 'whereas',
      ja_sentence: '車の利用は増えた一方で、バスの利用は減少した。',
      model_answer: 'Car use increased, whereas bus use declined.',
      tips: 'whereas は2つの対照的な傾向を1文でまとめる時に便利です。',
      explanation: 'Task 1では「A increased, whereas B declined」の形を覚えると、比較を短く自然に書けます。whileも使えますが、whereasの方が少し書き言葉らしい響きです。',
    },
    {
      order: 2,
      word: 'account for',
      ja_sentence: '再生可能エネルギーは総発電量の約30%を占めていた。',
      model_answer: 'Renewable energy accounted for approximately 30% of total electricity production.',
      tips: 'accounted for + 数値 は「占めた」。approximatelyを添えると概数表現になります。',
      explanation: '「占める」は made up でも書けますが、accounted for はIELTS Task 1で非常に使いやすい表現です。total electricity production のように、何の全体かも明確にしましょう。',
    },
    {
      order: 3,
      word: 'peak',
      ja_sentence: '売上は2022年に1億2000万ドルでピークに達した。',
      model_answer: 'Sales peaked at 120 million dollars in 2022.',
      tips: 'peak at + 数値 + in + 年 の形で、最高点を簡潔に表せます。',
      explanation: 'reached a peak of 120 million dollars でもOKです。動詞 peak を使うと短く、グラフ説明らしい文になります。',
    },
    {
      order: 4,
      word: 'overall',
      ja_sentence: '全体として、オンライン学習を選ぶ学生の割合は着実に増加した。',
      model_answer: 'Overall, the proportion of students choosing online learning increased steadily.',
      tips: 'Overall はoverviewの冒頭に置きやすい語です。the proportion of students choosing... で「〜を選ぶ学生の割合」。',
      explanation: 'Task 1のoverviewでは細かい数字を全部書くより、全体傾向を1文で言うことが大切です。increased steadily は「着実に増えた」という自然な表現です。',
    },
  ],
}
